### ISSUE TITLE
Donation: Add an alternative to ko-fi

### ISSUE THREAD

**Issue by Raton-Laveur** [duolicious/duolicious-frontend#230]
Ko-fi uses Paypal, which rejects my debit card for unknown reasons. 

Please consider adding [buymeacoffee](https://www.buymeacoffee.com), which uses Stripe for payment processing.

**Comment by duogenesis** [comment]
Thanks for the info and for your willingness to donate. I just attempted to send a test donation to Duolicious it was declined too. I'll set up Stripe in a few hours and post back here when I'm done. Thanks again.

**Comment by duogenesis** [comment]
I've set up Ko-fi to use Stripe as its payment processor instead of PayPal. I was able to donate successfully via Ko-fi by using Stripe.

**Comment by Raton-Laveur** [comment]
Can confirm, donation went fine through Stripe. 

I can't seem to find a donation link on the website itself, be it the [FAQ](https://duolicious.app/faq/) or anywhere else - please consider adding a mention towards donating in the FAQ.
