### ISSUE TITLE
Large image uploads fail

### ISSUE THREAD

**Issue by kawuka** [duolicious/duolicious-frontend#250]
I tried to upload a 5MB image but it kept spinning forever. I opened the dev tools and saw that upload request fails with 413 http code as it should, however frontend (web at least) keeps sending the request forever. From a UX standpoint this is bad and the app should show some kind of an error informing users about the size limit.

Steps to reproduce:
- Go to a profile
- Select big image 
- In networks tab you should see request failing over and over but the spinner keeps spinning

**Comment by duogenesis** [comment]
Thanks! I think I intended the limit to be 10 MB. I just changed some settings on the server to hopefully make that so. You can try uploading again, if you like.

You're right that the UI doesn't provide enough feedback about that though. IIRC, it only provides that kind of feedback during onboarding. Though I'm not even sure of that much. tbh, I cut a lot of corners thinking I'd have more time to fix things before the number of users increased this much...

Anyway, thanks again for the report! I'll look into this more soon

**Comment by duogenesis** [comment]
Closed by https://github.com/duolicious/duolicious-frontend/pull/477. Thanks again for raising this issue, @kawuka
