### ISSUE TITLE
You're offline

### ISSUE THREAD

**Issue by problemspinsei** [duolicious/duolicious-frontend#252]
Every time i try to open messages or start messaging someone it says I'm offline. Problem started today and didn't happen at all yesterday/

**Comment by JinJin1848** [comment]
same, I can't even check my inbox on a browser

**Comment by Tom3kk** [comment]
Same here, the mobile app won't even open for me.

**Comment by duogenesis** [comment]
Sorry. It went viral on Twitter. Duolicious should be back now. I beefed-up
the server and traffic is subsiding too, so we should be good again.
