### ISSUE TITLE
Duolicious has always had problems loading for me, and now it's gotten worse, preventing the site from loading entirely.

### ISSUE THREAD

**Issue by propolisor** [duolicious/duolicious-frontend#253]
(Edit: The site now loads again, so I guess it not loading at all was temporary maintenance/downtime. However the general issue below still stands, and I again still do think auditing the site for the issues mentioned could be productive.

Edit 3: Okay it was loading but I'm not sure if it is again now.)

(Note sure whether to put this in frontend or backend; feel free to move)

Browser: Firefox ESR latest on desktop

Duolicious, just the basic/main page (whether logged in or out), has always had problems loading in my browser. Two requests, an OPTIONS or POST request (doesn't seem to matter which) to "https://api.duolicious.app/check-session-token", and an OPTIONS or GET request to "https://api.duolicious.app/stats", have traditionally tried to load over and over again, failing dozens if not hundreds of times with an "NS_BINDING_ABORT" error. However, leaving the page to load long enough would eventually cause them to, without any apparent change, finally each return a 200 response, at which point the entire site's main interface would load. This could sometimes take up to 20 minutes though, making me dread reloading the page.

Now the situation has gotten worse and I can't get the site to load at all. "CORS failed", "NS_ERROR_DOM_BAD_URI", and "NS_ERROR_NET_INTERRUPT" have been added to the frequently encountered error list, and the requests never go through at all no matter how much time is given for the page to load. 

I will also echo #252 in saying that the messaging interface is also independently unstable, with "You're offline" errors being frequent and unsolvable without a main page reload (which is not a fast process as mentioned). The "inbox-info" URL (don't have the exact link ATM as the site won't load) also often fails to respond properly even when the main page loads, meaning the inbox does not load and no notifications for new messages/intros are triggered despite an apparently fully loaded main page.

The other tabs, such as Traits, Search, Profile, etc. trigger this kind of behavior as well, though less frequently. (A Search reload triggers it a bit more frequently. Other actions meanwhile, such as joining or leaving a club, updating one's profile, etc. almost always work.)

I use decently complex Web pages in my browser such as Discord, Element, Proton, the Google suite, etc. without incident, so I don't think it's my browser. Unfortunately, and not to insult the maintainer here, Duolicious has been one of the most finicky, unstable, and generally unreliable Web services I've ever used. This issue has significantly inhibited my ability to use the site, including my ability to promptly respond to messages, and now it is stopping me from using it at all.

I don't necessarily have the expertise to do so, but I and I believe many users would appreciate it if the code that loads the main Web app and code that interfaces with the API in general could be fully audited for issues that might cause the errors above. I believe that many users who are not as patient as me might simply be abandoning the site entirely, perhaps never even signing up, upon encountering these errors. Thank you in advance.

(Edit 2: duolicious-status.pages.dev is also constantly fetched, like multiple times per second. I'm not sure of the importance of that, but it seems a bit excessive. It also seems to sometimes block the loading of the "inbox-info" URL, making that problem worse.)

**Comment by duogenesis** [comment]
Sorry. It went viral on Twitter. Duolicious should be back now. I beefed-up the server and traffic is subsiding too, so we should be good again.

Related: #252
