### ISSUE TITLE
Changed my mind about participating here: Duo admin, you are an a s s hat, piece of s h i t, and f a g g o t j a n n y loser for explicitly and exclusively courting and then constantly banning the 4chan audience constantly in favor of Twitter meme users who will abandon your site in a week. You are a s h i t t y programmer, your site won't last no matter what because it is barely usable even if you weren't a r e t a r d, and I genuinely hope you choke. Bye. 

### ISSUE THREAD

**Issue by propolisor** [duolicious/duolicious-frontend#262]
Enjoy running Tinder but worse and with less people... for a month, until again everyone will abandon you again, because your site's recent boost in "popularity" is only because of it being known as the "femcel dating site" (while you ban all of them).

**Comment by propolisor** [comment]
I just left a Duolicious page/instance open for hours. "inbox-info" never loaded at the beginning and was never triggered to load the entire time, making messages inaccessible.

Then after I reloaded and it did load immediately, a message then failed to sense, triggering the "You're offline" error and making the inbox viewvable but unusable again (as no individual conversations can be loaded).

This is the kind of stuff that has been happening even pre-Twitter.

**Comment by iFUCKINGHATEcomputers** [comment]
Are people using 4chan tags getting banned or what?

**Comment by duogenesis** [comment]
@iFUCKINGHATEcomputers No. I have list of bannable clubs. They almost all contain a slur, denote something related to paedophilia, or very strongly communicate malevolence to the protected categories. Simply joining the 4chan club isn't enough to get you banned.
