### ISSUE TITLE
Images not uploading due to NetworkError

### ISSUE THREAD

**Issue by QMMBZ** [duolicious/duolicious-frontend#268]
When I attempt to upload images to my account, it simply loads forever. Someone else reported their previously uploaded images had been deleted in addition to this, but I cannot confirm that part of the issue as I did not have any uploaded images when the problem started for me.

The console reads as follows:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.duolicious.app/profile-info. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 500.
Caught error while fetching https://api.duolicious.app/profile-info TypeError: NetworkError when attempting to fetch resource.

Wish I knew how to fix this.

Just wanted to add that I love that this is open source! :) Hope the devs have a wonderful day

**Comment by duogenesis** [comment]
I believe this was because of an outage. Please let me know otherwise.
