### ISSUE TITLE
Maximum distance selection imprecision

### ISSUE THREAD

**Issue by sdasda7777** [duolicious/duolicious-frontend#269]
The distance selection seems to have the very common UI issue where it is hard to enter "small values" like 100 kms precisely, because the maximum value of the slider is comparatively astronomical. The issue in theory exists in age sliders as well, but it's not that much of an issue in practice there, because the maximum age is not comparatively astronomical.

I'm not aware of any perfect solution, but it's somewhat common to have an additional numeric box input where an exact value can be written into.

**Comment by duogenesis** [comment]
Closed by #295, #303
