### ISSUE TITLE
"We couldn't send an email there" isn't informative enough

### ISSUE THREAD

**Issue by duogenesis** [duolicious/duolicious-frontend#283]
`components/welcome-screen.tsx` is where this message is show. There's a few cases to consider:

* HTTP 429 - The message should be "You're doing that too much"
* HTTP 403 - "Account was banned"
* HTTP 4xx - "We couldn't send an email there"
* Other errors - "We couldn't connect to Duolicious"

Make sure to use smart quotes

**Comment by duogenesis** [comment]
Closed by #288 , #289

**Comment by ToaKraka** [comment]
This error message still isn't informative enough. I had to check DevTools to figure out that I received it because my email address was considered "disposable".

**Comment by duogenesis** [comment]
@ToaKraka Thanks for the feedback. I've addressed this in https://github.com/duolicious/duolicious-frontend/pull/751. Please let me know if you have further suggestions 🙂

**Comment by ToaKraka** [comment]
The new error message, "We don't support that email provider", is not necessarily correct. My email *provider* is Proton, but the filter is rejecting my email *domain*, firstnamelastname.com. But I guess you don't want to confuse technically-illiterate users.

(For the record, I just signed up with a separate Gmail account.)
