### ISSUE TITLE
add throuple dating mode

### ISSUE THREAD

**Issue by TheScreechingBagel** [duolicious/duolicious-frontend#317]
if three people all match with each other, they get thrown together into a groupchat

**Comment by TheScreechingBagel** [comment]
maybe after all three write a unique opening message for the other two, and all get sent at once

**Comment by duogenesis** [comment]
Triolicious

**Comment by duogenesis** [comment]
After thinking about this a little, I'm going to close this ticket. I want Duolicious to focus on long-term and monogamous dating.
