### ISSUE TITLE
Club Interactions / Stealing Clubs

### ISSUE THREAD

**Issue by kero3009destiny** [duolicious/duolicious-frontend#322]
Ability to click on a club pill to interact with that club, since search isn't a thing the only action that makes sense is to copying the user's club to own profile.

**Comment by wiki-me** [comment]
I would expect some details about the club, some of the listed clubs seem pretty cryptic and i don't know what they mean.

**Comment by duogenesis** [comment]
@wiki-me Good point. I've raised another ticket: https://github.com/duolicious/duolicious-frontend/issues/443
