### ISSUE TITLE
Make Q&A search filter more prominent

### ISSUE THREAD

**Issue by duogenesis** [duolicious/duolicious-frontend#403]
Lots of users seem unaware of the existence of Q&A search filters. I'm not sure if this is because the option isn't clearly labelled in the search filter screen. Although some users (a smaller group of users) seem unaware that search filters exist at all.

To make Q&A search filters more prominent, one user proposed a mechanic where users can "bookmark [questions] for the filter during the answering phase". The rationale is that while these questions might be important to the answering user, they might desire different responses depending on other search filters, like gender. For example, a person using Duolicious to look for male friends and female romantic partners might frequently switch between the following filters:

1. 
   a. Gender: Men
   b. Looking for: Friends
   c. With important Q&A answers (partly) disabled; but change their filters when looking for

2. 
   a. Gender: Woman
   b. Looking for: Relationship
   c. With important Q&A filters enforced

Some thought would need to be put into managing UX around the 20-question limit on Q&A search filters. There'd also need to be a way to clearly (an preferably visually) communicate to the user that the bookmarks are on a different screen than the Q&A tab.

Other ways to make Q&A search filters more prominent include:

* Moving the option up on the search filter page
* Relabelling the option

**Comment by wiki-me** [comment]
I have to admit i didn't know you can filter by anything, only after you mentioned it on reddit. iirc [gnome](https://en.wikipedia.org/wiki/GNOME) had a similar design (a three dots or something) for finding certain options and they did UX research showing it is basically investible.

I suggest changing it from those three lines on the search page to some string like "search filters" which seems like it is a lot more discoverable and harder to miss. after that i think finding the Q&A filter seems easy (maybe it is possible to gather data showing large percent of users hasn't visited the Q&A filter page which could refute what i am thinking).

**Comment by duogenesis** [comment]
> I have to admit i didn't know you can filter by anything

@wiki-me Are you using the web app, or mobile?

**Comment by wiki-me** [comment]
web app.
