### ISSUE TITLE
Remedies for the hard-to-solve bug where women do not use the service

### ISSUE THREAD

**Issue by ripandtearr** [duolicious/duolicious-frontend#98]
Hello, it's no secret that women don't use dating services in the same numbers as men.
And when they do, they flock to the big well-known names that appear when you type "what is a good dating app?" into your phone. Not the small new one on the block.

Consequently you need to brand your dating service in a very different way than existing services. "We have the best algorithm" won't cut it, technical arguments bounce off of women. You need an idea that sounds immediately attractive to someone hearing about it from their friend for the first time.

Some possible alternative brands that could be attractive to women:
- "media-dating": We're the service that matches you based on what quirky horror movies and music you like!! 
- "gamer-dating": Same as above but with a gamer focus. Guaranteed to get you free media coverage / viral twitter posts because of how funny 'gamer dating service' sounds
- "random-dating": Something like a dating-centric algorithmically-enhanced Omegle, which has a startling number of female users. 
- "alt-dating": We're the service that desperate incel/hikki/etc. men use (Just imagine the swathes of 'I can fix him' women running to Duolicious.)

Anyway these are just some quick ideas, you can think of more. Concept design and marketability will do more for your service than trying to create a more technically impressive algorithm.

Good luck & godspeed

**Comment by duogenesis** [comment]
I'm going to close this ticket because it's inactive and, as you mention, the solution is pretty much just to make Duolicious more mainstream, which is a nebulous and non-technical task with no definition of done.
